// Copyright (c) 2026, x_user_agent
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeUserAgentData: Hashable, CustomStringConvertible {
  var platform: String? = nil
  var platformVersion: String? = nil
  var model: String? = nil
  var architecture: String? = nil
  var appName: String? = nil
  var appVersion: String? = nil
  var buildNumber: String? = nil
  var packageName: String? = nil
  var mobile: Bool? = nil
  var device: String? = nil
  var brand: String? = nil
  var isEmulator: Bool? = nil
  var darwinVersion: String? = nil
  var cfnetworkVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeUserAgentData? {
    let platform: String? = nilOrValue(pigeonVar_list[0])
    let platformVersion: String? = nilOrValue(pigeonVar_list[1])
    let model: String? = nilOrValue(pigeonVar_list[2])
    let architecture: String? = nilOrValue(pigeonVar_list[3])
    let appName: String? = nilOrValue(pigeonVar_list[4])
    let appVersion: String? = nilOrValue(pigeonVar_list[5])
    let buildNumber: String? = nilOrValue(pigeonVar_list[6])
    let packageName: String? = nilOrValue(pigeonVar_list[7])
    let mobile: Bool? = nilOrValue(pigeonVar_list[8])
    let device: String? = nilOrValue(pigeonVar_list[9])
    let brand: String? = nilOrValue(pigeonVar_list[10])
    let isEmulator: Bool? = nilOrValue(pigeonVar_list[11])
    let darwinVersion: String? = nilOrValue(pigeonVar_list[12])
    let cfnetworkVersion: String? = nilOrValue(pigeonVar_list[13])

    return NativeUserAgentData(
      platform: platform,
      platformVersion: platformVersion,
      model: model,
      architecture: architecture,
      appName: appName,
      appVersion: appVersion,
      buildNumber: buildNumber,
      packageName: packageName,
      mobile: mobile,
      device: device,
      brand: brand,
      isEmulator: isEmulator,
      darwinVersion: darwinVersion,
      cfnetworkVersion: cfnetworkVersion
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      platformVersion,
      model,
      architecture,
      appName,
      appVersion,
      buildNumber,
      packageName,
      mobile,
      device,
      brand,
      isEmulator,
      darwinVersion,
      cfnetworkVersion,
    ]
  }
  static func == (lhs: NativeUserAgentData, rhs: NativeUserAgentData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.platform, rhs.platform) && MessagesPigeonInternal.deepEquals(lhs.platformVersion, rhs.platformVersion) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.architecture, rhs.architecture) && MessagesPigeonInternal.deepEquals(lhs.appName, rhs.appName) && MessagesPigeonInternal.deepEquals(lhs.appVersion, rhs.appVersion) && MessagesPigeonInternal.deepEquals(lhs.buildNumber, rhs.buildNumber) && MessagesPigeonInternal.deepEquals(lhs.packageName, rhs.packageName) && MessagesPigeonInternal.deepEquals(lhs.mobile, rhs.mobile) && MessagesPigeonInternal.deepEquals(lhs.device, rhs.device) && MessagesPigeonInternal.deepEquals(lhs.brand, rhs.brand) && MessagesPigeonInternal.deepEquals(lhs.isEmulator, rhs.isEmulator) && MessagesPigeonInternal.deepEquals(lhs.darwinVersion, rhs.darwinVersion) && MessagesPigeonInternal.deepEquals(lhs.cfnetworkVersion, rhs.cfnetworkVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeUserAgentData")
    MessagesPigeonInternal.deepHash(value: platform, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: platformVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: architecture, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: buildNumber, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: packageName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: mobile, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: device, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: brand, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isEmulator, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: darwinVersion, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: cfnetworkVersion, hasher: &hasher)
  }

  public var description: String {
    return "NativeUserAgentData(platform: \(String(describing: platform)), platformVersion: \(String(describing: platformVersion)), model: \(String(describing: model)), architecture: \(String(describing: architecture)), appName: \(String(describing: appName)), appVersion: \(String(describing: appVersion)), buildNumber: \(String(describing: buildNumber)), packageName: \(String(describing: packageName)), mobile: \(String(describing: mobile)), device: \(String(describing: device)), brand: \(String(describing: brand)), isEmulator: \(String(describing: isEmulator)), darwinVersion: \(String(describing: darwinVersion)), cfnetworkVersion: \(String(describing: cfnetworkVersion)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeUserAgentData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeUserAgentData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol XUserAgentApi {
  func getWebViewUserAgent(completion: @escaping (Result<String?, Error>) -> Void)
  func getSystemUserAgent(completion: @escaping (Result<String?, Error>) -> Void)
  func getUserAgentData(completion: @escaping (Result<NativeUserAgentData?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class XUserAgentApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `XUserAgentApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: XUserAgentApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getWebViewUserAgentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getWebViewUserAgent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWebViewUserAgentChannel.setMessageHandler { _, reply in
        api.getWebViewUserAgent { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getWebViewUserAgentChannel.setMessageHandler(nil)
    }
    let getSystemUserAgentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getSystemUserAgent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSystemUserAgentChannel.setMessageHandler { _, reply in
        api.getSystemUserAgent { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSystemUserAgentChannel.setMessageHandler(nil)
    }
    let getUserAgentDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getUserAgentData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserAgentDataChannel.setMessageHandler { _, reply in
        api.getUserAgentData { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getUserAgentDataChannel.setMessageHandler(nil)
    }
  }
}
