// Copyright (c) 2026, x_user_agent
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class NativeUserAgentData {
  NativeUserAgentData({
    this.platform,
    this.platformVersion,
    this.model,
    this.architecture,
    this.appName,
    this.appVersion,
    this.buildNumber,
    this.packageName,
    this.mobile,
    this.device,
    this.brand,
    this.isEmulator,
    this.darwinVersion,
    this.cfnetworkVersion,
  });

  String? platform;

  String? platformVersion;

  String? model;

  String? architecture;

  String? appName;

  String? appVersion;

  String? buildNumber;

  String? packageName;

  bool? mobile;

  String? device;

  String? brand;

  bool? isEmulator;

  String? darwinVersion;

  String? cfnetworkVersion;

  List<Object?> _toList() {
    return <Object?>[
      platform,
      platformVersion,
      model,
      architecture,
      appName,
      appVersion,
      buildNumber,
      packageName,
      mobile,
      device,
      brand,
      isEmulator,
      darwinVersion,
      cfnetworkVersion,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeUserAgentData decode(Object result) {
    result as List<Object?>;
    return NativeUserAgentData(
      platform: result[0] as String?,
      platformVersion: result[1] as String?,
      model: result[2] as String?,
      architecture: result[3] as String?,
      appName: result[4] as String?,
      appVersion: result[5] as String?,
      buildNumber: result[6] as String?,
      packageName: result[7] as String?,
      mobile: result[8] as bool?,
      device: result[9] as String?,
      brand: result[10] as String?,
      isEmulator: result[11] as bool?,
      darwinVersion: result[12] as String?,
      cfnetworkVersion: result[13] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeUserAgentData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platform, other.platform) &&
        _deepEquals(platformVersion, other.platformVersion) &&
        _deepEquals(model, other.model) &&
        _deepEquals(architecture, other.architecture) &&
        _deepEquals(appName, other.appName) &&
        _deepEquals(appVersion, other.appVersion) &&
        _deepEquals(buildNumber, other.buildNumber) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(mobile, other.mobile) &&
        _deepEquals(device, other.device) &&
        _deepEquals(brand, other.brand) &&
        _deepEquals(isEmulator, other.isEmulator) &&
        _deepEquals(darwinVersion, other.darwinVersion) &&
        _deepEquals(cfnetworkVersion, other.cfnetworkVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeUserAgentData(platform: $platform, platformVersion: $platformVersion, model: $model, architecture: $architecture, appName: $appName, appVersion: $appVersion, buildNumber: $buildNumber, packageName: $packageName, mobile: $mobile, device: $device, brand: $brand, isEmulator: $isEmulator, darwinVersion: $darwinVersion, cfnetworkVersion: $cfnetworkVersion)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeUserAgentData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeUserAgentData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class XUserAgentApi {
  /// Constructor for [XUserAgentApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  XUserAgentApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String?> getWebViewUserAgent() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.x_user_agent.XUserAgentApi.getWebViewUserAgent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<String?> getSystemUserAgent() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.x_user_agent.XUserAgentApi.getSystemUserAgent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<NativeUserAgentData?> getUserAgentData() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.x_user_agent.XUserAgentApi.getUserAgentData$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as NativeUserAgentData?;
  }
}
