// Copyright (c) 2026, x_user_agent
// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeUserAgentData (
  val platform: String? = null,
  val platformVersion: String? = null,
  val model: String? = null,
  val architecture: String? = null,
  val appName: String? = null,
  val appVersion: String? = null,
  val buildNumber: String? = null,
  val packageName: String? = null,
  val mobile: Boolean? = null,
  val device: String? = null,
  val brand: String? = null,
  val isEmulator: Boolean? = null,
  val darwinVersion: String? = null,
  val cfnetworkVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeUserAgentData {
      val platform = pigeonVar_list[0] as String?
      val platformVersion = pigeonVar_list[1] as String?
      val model = pigeonVar_list[2] as String?
      val architecture = pigeonVar_list[3] as String?
      val appName = pigeonVar_list[4] as String?
      val appVersion = pigeonVar_list[5] as String?
      val buildNumber = pigeonVar_list[6] as String?
      val packageName = pigeonVar_list[7] as String?
      val mobile = pigeonVar_list[8] as Boolean?
      val device = pigeonVar_list[9] as String?
      val brand = pigeonVar_list[10] as String?
      val isEmulator = pigeonVar_list[11] as Boolean?
      val darwinVersion = pigeonVar_list[12] as String?
      val cfnetworkVersion = pigeonVar_list[13] as String?
      return NativeUserAgentData(platform, platformVersion, model, architecture, appName, appVersion, buildNumber, packageName, mobile, device, brand, isEmulator, darwinVersion, cfnetworkVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      platformVersion,
      model,
      architecture,
      appName,
      appVersion,
      buildNumber,
      packageName,
      mobile,
      device,
      brand,
      isEmulator,
      darwinVersion,
      cfnetworkVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeUserAgentData
    return MessagesPigeonUtils.deepEquals(this.platform, other.platform) && MessagesPigeonUtils.deepEquals(this.platformVersion, other.platformVersion) && MessagesPigeonUtils.deepEquals(this.model, other.model) && MessagesPigeonUtils.deepEquals(this.architecture, other.architecture) && MessagesPigeonUtils.deepEquals(this.appName, other.appName) && MessagesPigeonUtils.deepEquals(this.appVersion, other.appVersion) && MessagesPigeonUtils.deepEquals(this.buildNumber, other.buildNumber) && MessagesPigeonUtils.deepEquals(this.packageName, other.packageName) && MessagesPigeonUtils.deepEquals(this.mobile, other.mobile) && MessagesPigeonUtils.deepEquals(this.device, other.device) && MessagesPigeonUtils.deepEquals(this.brand, other.brand) && MessagesPigeonUtils.deepEquals(this.isEmulator, other.isEmulator) && MessagesPigeonUtils.deepEquals(this.darwinVersion, other.darwinVersion) && MessagesPigeonUtils.deepEquals(this.cfnetworkVersion, other.cfnetworkVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platform)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.platformVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.architecture)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.appVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.buildNumber)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.packageName)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.mobile)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.device)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.brand)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isEmulator)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.darwinVersion)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.cfnetworkVersion)
    return result
  }
  override fun toString(): String {
    return "NativeUserAgentData(platform=$platform, platformVersion=$platformVersion, model=$model, architecture=$architecture, appName=$appName, appVersion=$appVersion, buildNumber=$buildNumber, packageName=$packageName, mobile=$mobile, device=$device, brand=$brand, isEmulator=$isEmulator, darwinVersion=$darwinVersion, cfnetworkVersion=$cfnetworkVersion)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeUserAgentData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeUserAgentData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface XUserAgentApi {
  fun getWebViewUserAgent(callback: (Result<String?>) -> Unit)
  fun getSystemUserAgent(callback: (Result<String?>) -> Unit)
  fun getUserAgentData(callback: (Result<NativeUserAgentData?>) -> Unit)

  companion object {
    /** The codec used by XUserAgentApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `XUserAgentApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: XUserAgentApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getWebViewUserAgent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getWebViewUserAgent{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getSystemUserAgent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSystemUserAgent{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.x_user_agent.XUserAgentApi.getUserAgentData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getUserAgentData{ result: Result<NativeUserAgentData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
